# Generated by Django 4.2 on 2025-07-02 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_productmodel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='category',
            new_name='product_category',
        ),
    ]
